function eStopGUI()
    global estopBtnHandle ResumebtnHandle
    % Create main figure for GUI
    mainFig = figure('Name', 'Control Panel', 'NumberTitle', 'off', 'Position', [100, 100, 700, 200], 'Color', [0.8 0.8 0.8]);

    % Button for "Press to Run"
    uicontrol('Style', 'pushbutton', 'String', 'Async Sensor Detection', ...
        'Position', [50, 50, 175, 100], ...
        'Callback', @toggleStop, ...
        'FontSize', 10, ...
        'BackgroundColor', [0.2 0.6 0.2], ...
        'ForegroundColor', [1 1 1], ...
        'Tag', 'person');

    % Button for "Delete Person"
    uicontrol('Style', 'pushbutton', 'String', 'Delete Person', ...
        'Position', [50, 40, 175, 50], ...  % Adjusted y position and height
        'Callback', @toggleStop, ...  % Replace this with an appropriate callback function if necessary
        'FontSize', 10, ...
        'BackgroundColor', [0.7 0.7 0.7], ...
        'ForegroundColor', [1 1 1], ...
        'Tag', 'deletePerson');

    % Button for "E-Stop"
    estopBtnHandle = uicontrol('Style', 'pushbutton', 'String', 'E-Stop', ...
        'Position', [275, 50, 175, 100], ...
        'Callback', @toggleStop, ...
        'FontSize', 10, ...
        'BackgroundColor', [1, 0.5, 0], ...
        'ForegroundColor', [1 1 1], ...
        'Tag', 'emergency');

    % Resume Button
    ResumebtnHandle = uicontrol('Style', 'pushbutton', 'String', 'Resume', ...
        'Position', [275+225, 50, 175, 100], ...
        'Callback', @toggleStop, ...
        'FontSize', 10, ...
        'BackgroundColor', [0.2 0.6 0.2], ...
        'ForegroundColor', [1 1 1], ...
        'Tag', 'resume');
end